hl.on("hyprland.start", function()
	hl.exec_cmd("hypridle")
	-- hl.exec_cmd("~/.config/hypr/scripts/waybar-autohide.sh")
	hl.exec_cmd("waybar")
	hl.exec_cmd("openrgb --startminimized")
	hl.exec_cmd("awww-daemon")
	hl.exec_cmd("~/.config/hypr/restore-wallpaper.sh")
	hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
	hl.exec_cmd("pypr")
	hl.exec_cmd("~/.config/hypr/lid-handle.sh")
	hl.exec_cmd("pulseaudio")
	hl.exec_cmd("mako")
	hl.exec_cmd("USE_LAYER_SHELL=0 vicinae server")
	hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &")
	hl.exec_cmd("walker --gapplication-service")
	hl.exec_cmd("elephant")
	hl.exec_cmd("auto-cpufreq --start")
	hl.exec_cmd("brightnessctl set 50%")
	hl.exec_cmd("pactl set-sink-volume @DEFAULT_SINK@ 0%")
	hl.exec_cmd("powertop --auto-tune")
end)

hl.env("XCURSOR_THEME", "Bibata-Modern-Ice")
hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_THEME", "Bibata-Modern-Ice")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("ELECTRON_OZONE_PLATFORM_HINT", "wayland")
hl.env("MOZ_ENABLE_WAYLAND", "1")
hl.env("GDK_SCALE", "1")
