hl.workspace_rule({ workspace = "special:top", on_created_empty = "discord", animation = "slidefadevert" })
hl.workspace_rule({ workspace = "special:bottom", on_created_empty = "steam", animation = "slidefadevert" })
hl.workspace_rule({ workspace = "special:left", on_created_empty = "gtk-launch youtube", animation = "slidefade" })
hl.workspace_rule({ workspace = "special:right", on_created_empty = "deadlock-modmanager", animation = "slidefade" })

hl.workspace_rule({ workspace = 1, monitor = "DP-2" })
hl.workspace_rule({ workspace = 2, monitor = "DP-2" })
hl.workspace_rule({ workspace = 3, monitor = "DP-2" })
hl.workspace_rule({ workspace = 4, monitor = "DP-1" })
hl.workspace_rule({ workspace = 5, monitor = "DP-1" })
hl.workspace_rule({ workspace = 6, monitor = "DP-1" })
hl.workspace_rule({ workspace = 7, monitor = "HDMI-A-2" })
hl.workspace_rule({ workspace = 8, monitor = "HDMI-A-2" })
hl.workspace_rule({ workspace = 9, monitor = "HDMI-A-2" })
