hl.workspace_rule({ workspace = "special:top", on_created_empty = "discord", animation = "slidefadevert" })
hl.workspace_rule({ workspace = "special:bottom", on_created_empty = "steam", animation = "slidefadevert" })
hl.workspace_rule({ workspace = "special:left", on_created_empty = "gtk-launch youtube", animation = "slidefade" })
hl.workspace_rule({ workspace = "special:right", on_created_empty = "deadlock-modmanager", animation = "slidefade" })
hl.workspace_rule({ workspace = "special:spot", on_created_empty = "spotify", animation = "slidefade" })

hl.workspace_rule({ workspace = 1, monitor = MONITOR_LG })
hl.workspace_rule({ workspace = 2, monitor = MONITOR_LG })
hl.workspace_rule({ workspace = 3, monitor = MONITOR_LG })
hl.workspace_rule({ workspace = 4, monitor = MONITOR_ACER })
hl.workspace_rule({ workspace = 5, monitor = MONITOR_ACER })
hl.workspace_rule({ workspace = 6, monitor = MONITOR_ACER })
hl.workspace_rule({ workspace = 7, monitor = MONITOR_HDMI })
hl.workspace_rule({ workspace = 8, monitor = MONITOR_HDMI })
hl.workspace_rule({ workspace = 9, monitor = MONITOR_HDMI })
