monitorv2 {
  output=eDP-1
  mode=1920x1200@60.00
  position=0x0
  scale=1.20
}

monitorv2 {
  output=DP-1
  mode=2560x1440@179.88
  position=auto-right
  scale=1.33
  vrr=1
}

monitorv2 {
  output=DP-2
  mode=1920x1080@240
  position=auto-left
  scale=1
}

monitorv2 {
  output=HDMI-A-2
  mode=1920x1080@60
  position=auto-right
  scale=1
  addreserved=30,30,45,45
}

